try
{
    Calculator.Add( 1, 1 );
}
catch ( Exception ex )
{
    Console.WriteLine( ex );
}